# Generated by Django 4.1 on 2022-09-05 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='section',
            name='tag_s',
            field=models.CharField(max_length=50, verbose_name='Название раздела'),
        ),
        migrations.CreateModel(
            name='MainSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной')),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='articles.article')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.section')),
            ],
            options={
                'verbose_name': 'Тема',
            },
        ),
    ]
