# Generated by Django 4.1 on 2022-09-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options_alter_section_tag_s_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='mainsection',
            options={'ordering': ['section'], 'verbose_name': 'Тема'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['tag_name'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.RenameField(
            model_name='section',
            old_name='tag_s',
            new_name='tag_name',
        ),
        migrations.RemoveField(
            model_name='section',
            name='articles_s',
        ),
        migrations.AddField(
            model_name='section',
            name='articles',
            field=models.ManyToManyField(related_name='sections', through='articles.MainSection', to='articles.article'),
        ),
    ]
