# Generated by Django 4.1 on 2022-09-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_options_alter_mainsection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainsection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='section',
            name='tag_name',
            field=models.CharField(max_length=50, verbose_name='Название тега'),
        ),
    ]
